translation_rest:
    resource: "@TranslationBundle/Controller/Rest/TranslationEntryController.php"
    type: "annotation"
    prefix: "/core/%internal_api_prefix%/translation"

translation:
    resource: "@TranslationBundle/Controller/DefaultController.php"
    type: "annotation"
    prefix: "/translation"
