variables:
    CONTAINER_IMAGE: registry.gitlab.ats-digital.com/ats/docker:php7.2
    DOCKER_DRIVER: overlay2

services:
    - mongo:3.4

stages:
    - lint
    - test
    - sensio
    - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/

phpunit:
    image: $CONTAINER_IMAGE
    stage: test
    before_script:
        - touch .env
        - echo "LEADWIRE_DATABASE_NAME=leadwire" >> .env
        - echo "LEADWIRE_DATABASE_HOST=mongo" >> .env
        - echo "LEADWIRE_DATABASE_PORT=27017" >> .env
        - echo "LEADWIRE_APP_DOMAIN=leadwire.local" >> .env
        - echo "LEADWIRE_APP_SCHEME=http" >> .env
        - echo "LEADWIRE_STRIPE_SECRET_KEY=$TEST_LEADWIRE_STRIPE_SECRET_KEY" >> .env
        - echo "LEADWIRE_SUPER_USER_ADMIN_NAME=$TEST_LEADWIRE_SUPER_USER_ADMIN_NAME" >> .env
        - echo "LEADWIRE_MAILER_TRANSPORT=$TEST_LEADWIRE_MAILER_TRANSPORT" >> .env
        - echo "LEADWIRE_MAILER_USER=$TEST_LEADWIRE_MAILER_USER" >> .env
        - echo "LEADWIRE_MAILER_PASSWORD=$TEST_LEADWIRE_MAILER_PASSWORD" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_ID=$TEST_LEADWIRE_GITHUB_CLIENT_ID" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_SECRET=$TEST_LEADWIRE_GITHUB_CLIENT_SECRET" >> .env
        - echo "LEADWIRE_JWT_TOKEN_SECRET=$TEST_LEADWIRE_JWT_TOKEN_SECRET" >> .env
        - echo "LEADWIRE_LDAP_HOST=$TEST_LEADWIRE_LDAP_HOST" >> .env
        - echo "LEADWIRE_LDAP_PORT=$TEST_LEADWIRE_LDAP_PORT" >> .env
        - echo "LEADWIRE_LDAP_DN_USER=$TEST_LEADWIRE_LDAP_DN_USER" >> .env
        - echo "LEADWIRE_LDAP_PASSWORD=$TEST_LEADWIRE_LDAP_PASSWORD" >> .env
        - echo "LEADWIRE_KIBANA_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_ES_USERNAME=$TEST_LEADWIRE_ES_USERNAME" >> .env
        - echo "LEADWIRE_ES_PASSWORD=$TEST_LEADWIRE_ES_PASSWORD" >> .env
        - echo "LEADWIRE_ES_HOST=$TEST_LEADWIRE_ES_HOST" >> .env
        - echo "LEADWIRE_ES_PORT=$TEST_LEADWIRE_ES_PORT" >> .env
        - echo "LEADWIRE_LOGIN_METHOD=$LEADWIRE_LOGIN_METHOD" >> .env
        - echo "LEADWIRE_COMPAGNE_ENABLED=$LEADWIRE_COMPAGNE_ENABLED" >> .env
        - echo "LEADWIRE_JENKINS_URL=$LEADWIRE_JENKINS_URL" >> .env
        - echo "LEADWIRE_STRIPE_ENABLED=$LEADWIRE_STRIPE_ENABLED" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_USERNAME=$LEADWIRE_KIBANA_ADMIN_USERNAME" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_UUID=$LEADWIRE_KIBANA_ADMIN_UUID" >> .env
        - composer install
        - composer install
    tags:
        - phpunit
    script:
        - ./vendor/bin/simple-phpunit --coverage-text --colors=never --strict-coverage --disallow-test-output -c phpunit.xml.dist

phpcs:
    image: $CONTAINER_IMAGE
    stage: lint
    before_script:
        - touch .env
        - echo "LEADWIRE_DATABASE_NAME=leadwire" >> .env
        - echo "LEADWIRE_DATABASE_HOST=mongo" >> .env
        - echo "LEADWIRE_DATABASE_PORT=27017" >> .env
        - echo "LEADWIRE_APP_DOMAIN=leadwire.local" >> .env
        - echo "LEADWIRE_APP_SCHEME=http" >> .env
        - echo "LEADWIRE_STRIPE_SECRET_KEY=$TEST_LEADWIRE_STRIPE_SECRET_KEY" >> .env
        - echo "LEADWIRE_SUPER_USER_ADMIN_NAME=$TEST_LEADWIRE_SUPER_USER_ADMIN_NAME" >> .env
        - echo "LEADWIRE_MAILER_TRANSPORT=$TEST_LEADWIRE_MAILER_TRANSPORT" >> .env
        - echo "LEADWIRE_MAILER_USER=$TEST_LEADWIRE_MAILER_USER" >> .env
        - echo "LEADWIRE_MAILER_PASSWORD=$TEST_LEADWIRE_MAILER_PASSWORD" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_ID=$TEST_LEADWIRE_GITHUB_CLIENT_ID" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_SECRET=$TEST_LEADWIRE_GITHUB_CLIENT_SECRET" >> .env
        - echo "LEADWIRE_JWT_TOKEN_SECRET=$TEST_LEADWIRE_JWT_TOKEN_SECRET" >> .env
        - echo "LEADWIRE_LDAP_HOST=$TEST_LEADWIRE_LDAP_HOST" >> .env
        - echo "LEADWIRE_LDAP_PORT=$TEST_LEADWIRE_LDAP_PORT" >> .env
        - echo "LEADWIRE_LDAP_DN_USER=$TEST_LEADWIRE_LDAP_DN_USER" >> .env
        - echo "LEADWIRE_LDAP_PASSWORD=$TEST_LEADWIRE_LDAP_PASSWORD" >> .env
        - echo "LEADWIRE_KIBANA_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_ES_USERNAME=$TEST_LEADWIRE_ES_USERNAME" >> .env
        - echo "LEADWIRE_ES_PASSWORD=$TEST_LEADWIRE_ES_PASSWORD" >> .env
        - echo "LEADWIRE_ES_HOST=$TEST_LEADWIRE_ES_HOST" >> .env
        - echo "LEADWIRE_ES_PORT=$TEST_LEADWIRE_ES_PORT" >> .env
        - echo "LEADWIRE_LOGIN_METHOD=$LEADWIRE_LOGIN_METHOD" >> .env
        - echo "LEADWIRE_COMPAGNE_ENABLED=$LEADWIRE_COMPAGNE_ENABLED" >> .env
        - echo "LEADWIRE_JENKINS_URL=$LEADWIRE_JENKINS_URL" >> .env
        - echo "LEADWIRE_STRIPE_ENABLED=$LEADWIRE_STRIPE_ENABLED" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_USERNAME=$LEADWIRE_KIBANA_ADMIN_USERNAME" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_UUID=$LEADWIRE_KIBANA_ADMIN_UUID" >> .env
        - composer install
    tags:
        - phpunit
    script:
        - ./vendor/bin/phpcs --error-severity=1 --warning-severity=8 --extensions=php --standard=ats_ruleset.xml.dist --encoding=utf-8 ./src/AppBundle

phpstan:
    image: $CONTAINER_IMAGE
    stage: lint
    before_script:
        - touch .env
        - echo "LEADWIRE_DATABASE_NAME=leadwire" >> .env
        - echo "LEADWIRE_DATABASE_HOST=mongo" >> .env
        - echo "LEADWIRE_DATABASE_PORT=27017" >> .env
        - echo "LEADWIRE_APP_DOMAIN=leadwire.local" >> .env
        - echo "LEADWIRE_APP_SCHEME=http" >> .env
        - echo "LEADWIRE_STRIPE_SECRET_KEY=$TEST_LEADWIRE_STRIPE_SECRET_KEY" >> .env
        - echo "LEADWIRE_SUPER_USER_ADMIN_NAME=$TEST_LEADWIRE_SUPER_USER_ADMIN_NAME" >> .env
        - echo "LEADWIRE_MAILER_TRANSPORT=$TEST_LEADWIRE_MAILER_TRANSPORT" >> .env
        - echo "LEADWIRE_MAILER_USER=$TEST_LEADWIRE_MAILER_USER" >> .env
        - echo "LEADWIRE_MAILER_PASSWORD=$TEST_LEADWIRE_MAILER_PASSWORD" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_ID=$TEST_LEADWIRE_GITHUB_CLIENT_ID" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_SECRET=$TEST_LEADWIRE_GITHUB_CLIENT_SECRET" >> .env
        - echo "LEADWIRE_JWT_TOKEN_SECRET=$TEST_LEADWIRE_JWT_TOKEN_SECRET" >> .env
        - echo "LEADWIRE_LDAP_HOST=$TEST_LEADWIRE_LDAP_HOST" >> .env
        - echo "LEADWIRE_LDAP_PORT=$TEST_LEADWIRE_LDAP_PORT" >> .env
        - echo "LEADWIRE_LDAP_DN_USER=$TEST_LEADWIRE_LDAP_DN_USER" >> .env
        - echo "LEADWIRE_LDAP_PASSWORD=$TEST_LEADWIRE_LDAP_PASSWORD" >> .env
        - echo "LEADWIRE_KIBANA_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_ES_USERNAME=$TEST_LEADWIRE_ES_USERNAME" >> .env
        - echo "LEADWIRE_ES_PASSWORD=$TEST_LEADWIRE_ES_PASSWORD" >> .env
        - echo "LEADWIRE_ES_HOST=$TEST_LEADWIRE_ES_HOST" >> .env
        - echo "LEADWIRE_ES_PORT=$TEST_LEADWIRE_ES_PORT" >> .env
        - echo "LEADWIRE_LOGIN_METHOD=$LEADWIRE_LOGIN_METHOD" >> .env
        - echo "LEADWIRE_COMPAGNE_ENABLED=$LEADWIRE_COMPAGNE_ENABLED" >> .env
        - echo "LEADWIRE_JENKINS_URL=$LEADWIRE_JENKINS_URL" >> .env
        - echo "LEADWIRE_STRIPE_ENABLED=$LEADWIRE_STRIPE_ENABLED" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_USERNAME=$LEADWIRE_KIBANA_ADMIN_USERNAME" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_UUID=$LEADWIRE_KIBANA_ADMIN_UUID" >> .env
        - composer install
    tags:
        - phpunit
    script:
        - ./bin/console cache:clear --env dev
        - ./vendor/bin/phpstan analyse

sensio-insight:
    image: $CONTAINER_IMAGE
    stage: sensio
    tags:
        - php-qa
    script:
        - curl -o insight.phar -s https://get.insight.symfony.com/insight.phar
        - php insight.phar analyze --no-interaction --no-ansi 2d9d7311-a698-4ed2-b484-6c19f0211940 --reference $CI_COMMIT_SHA --user-uuid 2acbe908-0593-4401-a1ae-315ec03e025f --api-token b9b8faac9a8ade3d12b75b7a84e42d9dfc3ec4c3d19f680564dbfc98850d69fc --fail-condition "analysis.grade in ['none']"
    except:
        refs:
            - /^v[0-9]{1,}.*$/
    allow_failure: true

deploy:test:
    image: $CONTAINER_IMAGE
    stage: deploy
    tags:
        - min-runner
    environment:
        name: test
        url: http://leadwire.test.ats-digital.com
    only:
        - develop
    before_script:
        - touch .env
        - echo "LEADWIRE_DATABASE_NAME=leadwire" >> .env
        - echo "LEADWIRE_DATABASE_HOST=mongo" >> .env
        - echo "LEADWIRE_DATABASE_PORT=27017" >> .env
        - echo "LEADWIRE_APP_DOMAIN=leadwire.local" >> .env
        - echo "LEADWIRE_APP_SCHEME=http" >> .env
        - echo "LEADWIRE_STRIPE_SECRET_KEY=$TEST_LEADWIRE_STRIPE_SECRET_KEY" >> .env
        - echo "LEADWIRE_SUPER_USER_ADMIN_NAME=$TEST_LEADWIRE_SUPER_USER_ADMIN_NAME" >> .env
        - echo "LEADWIRE_MAILER_TRANSPORT=$TEST_LEADWIRE_MAILER_TRANSPORT" >> .env
        - echo "LEADWIRE_MAILER_USER=$TEST_LEADWIRE_MAILER_USER" >> .env
        - echo "LEADWIRE_MAILER_PASSWORD=$TEST_LEADWIRE_MAILER_PASSWORD" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_ID=$TEST_LEADWIRE_GITHUB_CLIENT_ID" >> .env
        - echo "LEADWIRE_GITHUB_CLIENT_SECRET=$TEST_LEADWIRE_GITHUB_CLIENT_SECRET" >> .env
        - echo "LEADWIRE_JWT_TOKEN_SECRET=$TEST_LEADWIRE_JWT_TOKEN_SECRET" >> .env
        - echo "LEADWIRE_LDAP_HOST=$TEST_LEADWIRE_LDAP_HOST" >> .env
        - echo "LEADWIRE_LDAP_PORT=$TEST_LEADWIRE_LDAP_PORT" >> .env
        - echo "LEADWIRE_LDAP_DN_USER=$TEST_LEADWIRE_LDAP_DN_USER" >> .env
        - echo "LEADWIRE_LDAP_PASSWORD=$TEST_LEADWIRE_LDAP_PASSWORD" >> .env
        - echo "LEADWIRE_KIBANA_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_HOST=$TEST_LEADWIRE_KIBANA_HOST" >> .env
        - echo "LEADWIRE_KIBANA_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_KIBANA_IFRAME_PORT=$TEST_LEADWIRE_KIBANA_PORT" >> .env
        - echo "LEADWIRE_ES_USERNAME=$TEST_LEADWIRE_ES_USERNAME" >> .env
        - echo "LEADWIRE_ES_PASSWORD=$TEST_LEADWIRE_ES_PASSWORD" >> .env
        - echo "LEADWIRE_ES_HOST=$TEST_LEADWIRE_ES_HOST" >> .env
        - echo "LEADWIRE_ES_PORT=$TEST_LEADWIRE_ES_PORT" >> .env
        - echo "LEADWIRE_LOGIN_METHOD=$LEADWIRE_LOGIN_METHOD" >> .env
        - echo "LEADWIRE_COMPAGNE_ENABLED=$LEADWIRE_COMPAGNE_ENABLED" >> .env
        - echo "LEADWIRE_JENKINS_URL=$LEADWIRE_JENKINS_URL" >> .env
        - echo "LEADWIRE_STRIPE_ENABLED=$LEADWIRE_STRIPE_ENABLED" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_USERNAME=$LEADWIRE_KIBANA_ADMIN_USERNAME" >> .env
        - echo "LEADWIRE_KIBANA_ADMIN_UUID=$LEADWIRE_KIBANA_ADMIN_UUID" >> .env
    script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$ATS_TEST_SSH_KEY")
        - mkdir -p ~/.ssh
        - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - scp .env ats@test.ats-digital.com:/apps/leadwire_lot2/.env
        - ssh -t ats@test.ats-digital.com 'cd /apps/leadwire_lot2 &&
            pwd &&
            rm -fr /apps/leadwire_lot2/var/cache/app/prod &&
            eval $(ssh-agent -s) &&
            git pull origin develop &&
            ssh-add ~/.ssh/deploy_rsa &&
            composer install --no-dev --no-scripts --optimize-autoloader &&
            app/console assets:install --env prod &&
            app/console assetic:dump --env prod &&
            app/console cache:clear --env prod
          '
