variables:
    CONTAINER_IMAGE: registry.gitlab.ats-digital.com/ats/docker:php7.2
    DOCKER_DRIVER: overlay2

services:
    - mongo:3.4

stages:
    # - test
    # - sensio
    - deploy

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - vendor/

# phpcs:
#     image: $CONTAINER_IMAGE
#     stage: test
#     before_script:
#         - composer install
#         - cp ./app/config/parameters.yml.dist ./app/config/parameters.yml
#     tags:
#         - phpunit
#     script:
#         - ./vendor/bin/phpcs --error-severity=1 --warning-severity=8 --extensions=php --standard=ats_ruleset.xml.dist --encoding=utf-8 ./src/AppBundle

# phpstan:
#     image: $CONTAINER_IMAGE
#     stage: test
#     before_script:
#         - composer install
#         - cp ./app/config/parameters.yml.dist ./app/config/parameters.yml
#     tags:
#         - phpunit
#     script:
#         - ./bin/console cache:clear --env dev
#         - ./vendor/bin/phpstan analyse

# sensio-insight:
#     image: $CONTAINER_IMAGE
#     stage: sensio
#     tags:
#         - php-qa
#     script:
#         - curl -o insight.phar -s https://get.insight.symfony.com/insight.phar
#         - php insight.phar analyze --no-interaction --no-ansi 2d9d7311-a698-4ed2-b484-6c19f0211940 --reference $CI_COMMIT_SHA --user-uuid 2acbe908-0593-4401-a1ae-315ec03e025f --api-token b9b8faac9a8ade3d12b75b7a84e42d9dfc3ec4c3d19f680564dbfc98850d69fc --fail-condition "analysis.grade in ['none']"
#     except:
#         refs:
#             - /^v[0-9]{1,}.*$/
#     allow_failure: true

deploy:test:
    image: $CONTAINER_IMAGE
    stage: deploy
    tags:
        - min-runner
    environment:
        name: test
        url: http://leadwire.test.ats-digital.com
    only:
        - develop
    script:
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$ATS_TEST_SSH_KEY")
        - mkdir -p ~/.ssh
        - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - ssh -t ats@test.ats-digital.com 'cd /apps/leadwire_lot2 &&
            pwd &&
            eval $(ssh-agent -s) &&
            git pull origin develop &&
            ssh-add ~/.ssh/deploy_rsa &&
            composer install --no-dev --no-scripts &&
            app/console assets:install --env prod &&
            app/console assetic:dump --env prod &&
            app/console cache:clear --env prod
          '
