pre_composer_script: |
    #!/bin/bash
    yes '' | pecl install mongodb

php_ini: |
    extension=mongodb.so

exclude_patterns:
    - app/check.php
    - app/SymfonyRequirements.php
    - web/config.php
    - web/app*.php
    - src/UIBundle/Resources/public/js/**/*.js
    - .gitlab-ci.yml

rules:
    symfony.controller.too_many_actions_per_controller:
        enabled: true
        max_count: 20
        threshold: 5