core_rest_upload:
    resource: "@CoreBundle/Controller/Rest/RestFileOperationController.php"
    type: "annotation"
    prefix: "/core/%internal_api_prefix%"
    host: "%app_domain%"
    schemes: "%app_schemes%"
