services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ATS\PaymentBundle\:
    resource: '../../*'
    exclude: '../../{Document,Repository,Message}'

  ats_payment.customer_service:
    class: ATS\PaymentBundle\Service\CustomerService
    autowire: true

  ats_payment.payment_service:
    class: ATS\PaymentBundle\Service\PaymentService
    autowire: true

  ats_payment.custom_stripe_gateway:
    class: ATS\PaymentBundle\Service\CustomStripeGateway
    arguments:
      - "%secret_key%"
  ATS\PaymentBundle\Service\CustomStripeGateway: "@ats_payment.custom_stripe_gateway"