imports:
    - { resource: config.yml }

monolog:
    handlers:
        main:
            type: rotating_file
            action_level: error
            max_files: 10
            level: error
            channels: ['!kibana', '!es', '!ldap']
        kibana:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/kibana.log'
            channels: [kibana]
        curator:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/curator.log'
            channels: [curator]
        es:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/es.log'
            channels: [es]
        ldap:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/ldap.log'
            channels: [ldap]
        auth:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/auth.log'
            channels: [auth]
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: error
        console:
            type: console
            process_psr_3_messages: false

sentry:
    dsn: "https://918b5864b38348e0948bcb7099ad6824:c59d5742338342198b7de15cde31843c@sentry.test.ats-digital.com/4"
