imports:
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: vendor/config.yml}
    - { resource: "@AppBundle/Resources/config/config.yml" }
    - { resource: "@CoreBundle/Resources/config/config.yml" }
    - { resource: "@UIBundle/Resources/config/services.yml" }
    - { resource: "@PaymentBundle/Resources/config/services.yml" }

# Parameters Configuration
parameters:
    locale: en
    app_version: 'v1.3.6'
    app_domain: '%env(LEADWIRE_APP_DOMAIN)%'
    app_schemes: '%env(LEADWIRE_APP_SCHEME)%'
    socket_io_port: '%env(LEADWIRE_SOCKET_IO_PORT)%'
    activation_code_regex: '[A-Z0-9]B[A-Z0-9]{2}7[A-Z0-9]'
    default_lock_message: 'Your account has been locked'
    secret: 06abd8f87b9d3b88feb152891421cb20017e56dd
    internal_api_prefix: api
    secret_key: '%env(LEADWIRE_STRIPE_SECRET_KEY)%'
    providerName: Stripe
    super_admin_username: '%env(LEADWIRE_SUPER_USER_ADMIN_NAME)%'
    mailer_transport: '%env(LEADWIRE_MAILER_TRANSPORT)%'
    mailer_host: '%env(LEADWIRE_MAILER_HOST)%'
    mailer_port: '%env(LEADWIRE_MAILER_PORT)%'
    mailer_user: '%env(LEADWIRE_MAILER_USER)%'
    mailer_password: '%env(LEADWIRE_MAILER_PASSWORD)%'
    sender: "%mailer_user%"
    github_client_id: '%env(LEADWIRE_GITHUB_CLIENT_ID)%'
    auth_providers.settings.token_secret: '%env(LEADWIRE_JWT_TOKEN_SECRET)%'
    kibana.host: '%env(LEADWIRE_KIBANA_HOST)%'
    kibana.iframe_host: '%env(LEADWIRE_KIBANA_IFRAME_HOST)%'
    kibana.port: '%env(LEADWIRE_KIBANA_PORT)%'
    kibana.iframe_port: '%env(LEADWIRE_KIBANA_IFRAME_PORT)%'
    login_method: '%env(LEADWIRE_LOGIN_METHOD)%'
    compagne_enabled: '%env(LEADWIRE_COMPAGNE_ENABLED)%'
    jenkins_url: '%env(LEADWIRE_JENKINS_URL)%'
    stripe_enabled: '%env(LEADWIRE_STRIPE_ENABLED)%'
    logout_url: '%env(LEADWIRE_LOGOUT_URL)%'
    kibana_admin_username: '%env(LEADWIRE_KIBANA_ADMIN_USERNAME)%'
    has_all_user_tenant: false
    auth_providers:
        github:
            github_access_token_url: 'https://github.com/login/oauth/access_token'
            github_users_api_url: 'https://api.github.com/user'
            github_client_secret: '%env(LEADWIRE_GITHUB_CLIENT_SECRET)%'
        settings:
            token_secret: '%env(LEADWIRE_JWT_TOKEN_SECRET)%'
    ldap:
        host: '%env(LEADWIRE_LDAP_HOST)%'
        port: '%env(LEADWIRE_LDAP_PORT)%'
        dn_user: '%env(LEADWIRE_LDAP_DN_USER)%'
        mdp: '%env(LEADWIRE_LDAP_PASSWORD)%'
    kibana:
        host: '%env(LEADWIRE_KIBANA_HOST)%'
        port: '%env(LEADWIRE_KIBANA_PORT)%'
        iframe_host: '%env(LEADWIRE_KIBANA_IFRAME_HOST)%'
        iframe_port: '%env(LEADWIRE_KIBANA_IFRAME_PORT)%'
        kibana_admin_username: '%env(LEADWIRE_KIBANA_ADMIN_USERNAME)%'
        kibana_admin_uuid: '%env(LEADWIRE_KIBANA_ADMIN_UUID)%'
        kibana_mailer_user: '%env(LEADWIRE_MAILER_USER)%'
        kibana_password: '%env(LEADWIRE_ES_PASSWORD)%'
    elastic:
        username: '%env(LEADWIRE_ES_USERNAME)%'
        password: '%env(LEADWIRE_ES_PASSWORD)%'
        host: '%env(LEADWIRE_ES_HOST)%'
        port: '%env(LEADWIRE_ES_PORT)%'
        ism_setup: '%env(LEADWIRE_ISM_SETUP)%'
        ism_min_size: '%env(LEADWIRE_ISM_MIN_SIZE)%'
        ism_min_doc_count: '%env(LEADWIRE_ISM_MIN_DOC_COUNT)%'
        ism_min_index_age: '%env(ISM_MIN_INDEX_Age)%'
    curator:
        platformName: '%env(LEADWIRE_PLATFORM_NAME)%'

# Framework Configuration
framework:
    translator:              { fallbacks: ['%locale%'] }
    secret:                  '%secret%'
    router:
        resource:            '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    validation:              { enable_annotations: true }
    templating:
        engines:             ['twig']
    default_locale:          '%locale%'
    trusted_hosts:           ~
    fragments:    ~
    http_method_override:    true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        APP_VERSION:  '%app_version%'
        LEADWIRE_APP_DOMAIN: '%app_domain%'
        LEADWIRE_SOCKET_IO_PORT: '%socket_io_port%'
        BASE_URL: '%app_schemes%://%app_domain%/'
        ASSETS_BASE_URL: '/'
        UPLOAD_URL: '%app_schemes%://%app_domain%/uploads/'
        DOWNLOAD_URL: '%app_schemes%://%app_domain%/core/api/resource/'
        LEADWIRE_GITHUB_CLIENT_ID: '%github_client_id%'
        KIBANA_BASE_URL: '%kibana.iframe_host%:%kibana.iframe_port%/'
        DATE_DEFAULT_FORMAT: 'YYYY-MM-DD[T]HH:mm:ssZZ'
        EN_DATE_FORMAT: 'YYYY-DD-MM'
        FR_DATE_FORMAT: 'DD-MM-YYYY'
        TAX: 20
        LEADWIRE_LOGIN_METHOD: '%login_method%'
        LEADWIRE_COMPAGNE_ENABLED: '%compagne_enabled%'
        LEADWIRE_JENKINS_URL: '%jenkins_url%'
        LEADWIRE_STRIPE_ENABLED: '%stripe_enabled%'
        LEADWIRE_LOGOUT_URL: '%logout_url%'
    paths:
        '%kernel.project_dir%/src/UIBundle/Resources/views/Default': ~

# Assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    bundles:
        - UIBundle

    filters:
        cssrewrite: ~

doctrine_mongodb:
    auto_generate_hydrator_classes: true
    default_database: '%env(LEADWIRE_DATABASE_NAME)%'
    default_connection: default
    default_document_manager: default
    connections:
        default:
            server: 'mongodb://%env(LEADWIRE_DATABASE_HOST)%:%env(LEADWIRE_DATABASE_PORT)%'
            options:
                connect: true
                db: '%env(LEADWIRE_DATABASE_NAME)%'
    document_managers:
        default:
            connection: default
            database: '%env(LEADWIRE_DATABASE_NAME)%'
            auto_mapping: true
