imports:
    - { resource: config.yml }
    - { resource: services_dev.yml }

parameters:
    dev_delivery_address: aturki@ats-digital.com

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event', '!kibana', '!es', '!ldap']
        kibana:
            type: stream
            action_level: notice
            level: notice
            path:     '%kernel.logs_dir%/kibana_%kernel.environment%.log'
            channels: [kibana]
        curator:
            type: stream
            action_level: notice
            level: notice
            path:     '%kernel.logs_dir%/curator_%kernel.environment%.log'
            channels: [curator]
        es:
            type: stream
            action_level: notice
            level: notice
            path:     '%kernel.logs_dir%/es_%kernel.environment%.log'
            channels: [es]
        ldap:
            type: stream
            action_level: notice
            level: notice
            path:     '%kernel.logs_dir%/ldap_%kernel.environment%.log'
            channels: [ldap]
        auth:
            type: stream
            action_level: notice
            level: notice
            path:     '%kernel.logs_dir%/auth_%kernel.environment%.log'
            channels: [auth]
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911

swiftmailer:
    delivery_addresses:
        - "%dev_delivery_address%"
    logging: true

nelmio_cors:
    paths:
        '^/login':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '/core/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            max_age: 3600
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
