imports:
    - { resource: config.yml }
    - { resource: services_dev.yml }

parameters:
    dev_delivery_address: aturki@ats-digital.com

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event', '!kibana', '!es', '!ldap']
        kibana:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/kibana.log'
            channels: [kibana]
        sg:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/search_guard.log'
            channels: [search_guard]
        es:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/es.log'
            channels: [es]
        ldap:
            type: rotating_file
            action_level: notice
            max_files: 10
            level: notice
            path:     '%kernel.logs_dir%/ldap.log'
            channels: [ldap]
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

swiftmailer:
    delivery_addresses:
        - "%dev_delivery_address%"
    logging: true

nelmio_cors:
    paths:
        '^/login':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '/core/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            max_age: 3600
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
