ui:
    resource: "@UIBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   "/"
    host:     "%app_domain%"
    schemes: "%app_schemes%"

payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   "/"
    host:     "%app_domain%"
    schemes: "%app_schemes%"

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   "/"
    host:     "%app_domain%"
    schemes:  "%app_schemes%"

email:
    resource: "@EmailBundle/Resources/config/routing.yml"
    prefix:   "/"
    host:     "%app_domain%"
    schemes:  "%app_schemes%"

# translation:
#     resource: "@TranslationBundle/Resources/config/routing.yml"
#     prefix:   "/"
#     host:     "%app_domain%"
#     schemes:  "%app_schemes%"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    host:     "%app_domain%"
    schemes:  "%app_schemes%"
