security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        simple_user_provider:
            id: APpBundle\Provider\SimpleUserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|login)/
            security: false
        api:
            pattern:  ^(/core)?/%internal_api_prefix%((?!/translation|/context))
            provider: simple_user_provider
            stateless: true
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator

    access_control:
        - { path: ^/login,                             roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/core/%internal_api_prefix%,        roles: [ ROLE_USER ] }
        - { path: ^/%internal_api_prefix%,             roles: [ ROLE_USER ] }
