security:
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        simple_user_provider:
            id: AppBundle\Provider\SimpleUserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|login)/
            security: false
        health_check:
            pattern: /api/process/login/get
            security: false
        api:
            pattern:  ^(/core)?/%internal_api_prefix%
            provider: simple_user_provider
            stateless: true
            security: true
            guard:
                authenticators:
                    - AppBundle\Security\TokenAuthenticator
