services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    jms_serializer.naming_strategy:
        alias: jms_serializer.identical_property_naming_strategy
    # Making the logger service public
    logger:
        alias: 'monolog.logger'
        public: true

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Document,Repository}'

    ATS\CoreBundle\:
        resource: '../../src/ATS/CoreBundle/*'
        exclude: '../../src/ATS/CoreBundle/{Document,Repository}'

    ATS\EmailBundle\:
        resource: '../../src/ATS/EmailBundle/*'
        exclude: '../../src/ATS/EmailBundle/{Document,Repository}'

    ATS\TranslationBundle\:
        resource: '../../src/ATS/TranslationBundle/*'
        exclude: '../../src/ATS/TranslationBundle/{Document,Repository}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    AppBundle\Service\LdapService:
        arguments:
            $settings: '%ldap%'

    AppBundle\Service\ElasticSearchService:
        arguments:
            $env: "%kernel.environment%"
            $settings: "%elastic%"

    AppBundle\Service\KibanaService:
        arguments:
            $settings: "%kibana%"

    AppBundle\Service\InvitationService:
        arguments:
            $sender: "%sender%"

    AppBundle\Service\UserService:
        arguments:
            $sender: "%sender%"

    AppBundle\Service\AuthService:
        arguments:
            $appDomain: "%app_domain%"
            $authProviderSettings: "%auth_providers%"

    AppBundle\Service\ApplicationTypeService:
        arguments:
            $dataRootPath: "%kernel.project_dir%/app/Resources/Kibana"
