app_default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type: "annotation"
    prefix: "/"

app_rest_app:
    resource: "@AppBundle/Controller/Rest/ApplicationController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/app"

app_rest_invitation:
    resource: "@AppBundle/Controller/Rest/InvitationController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/invitation"

app_rest_user:
    resource: "@AppBundle/Controller/Rest/UserController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/user"

app_rest_auth:
    resource: "@AppBundle/Controller/Rest/AuthController.php"
    type: "annotation"
    prefix: "/login"

app_rest_applicationtype:
    resource: "@AppBundle/Controller/Rest/ApplicationTypeController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/applicationType"

app_rest_activation_code:
    resource: "@AppBundle/Controller/Rest/ActivationCodeController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/activation-code"

app_rest_template:
    resource: "@AppBundle/Controller/Rest/TemplateController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/template"

app_rest_monitoringset:
    resource: "@AppBundle/Controller/Rest/MonitoringSetController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/monitoringSet"

app_rest_tmec:
    resource: "@AppBundle/Controller/Rest/TmecController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/tmec"

app_rest_step:
    resource: "@AppBundle/Controller/Rest/StepController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/step"

app_rest_environment:
    resource: "@AppBundle/Controller/Rest/EnvironmentController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/environment"

app_rest_overview:
    resource: "@AppBundle/Controller/Rest/OverviewController.php"
    type: "annotation"
    prefix: "/%internal_api_prefix%/overview"
