parameters:
    admin_routes_prefix: "admin"
services:
    admin.routes_loader:
        class: "ATS\\AdminBundle\\Routing\\RoutesLoader"
        arguments:
            - "@doctrine_mongodb"
            - "%admin_routes_prefix%"
            - "%app_schemes%"
            - "%app_domain%"
        tags:
            - "routing.loader"

    admin.type_guesser:
        public: true
        class: "ATS\\AdminBundle\\Form\\AdminTypeGuesser"
        arguments:
            - "@doctrine_mongodb"
