services:
    analytics.map_discriminator.listener:
        class: "ATS\\AnalyticsBundle\\Listener\\MapDiscriminatorListener"
        arguments:
            - "%analytics.discriminator_map%"
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }


    ATS\AnalyticsBundle\Listener\AnalyticsEventListener:
        tags:
            - { name: kernel.event_listener }
